services:
  redis-redlock:
    image: redis:8.2.0-alpine
    command: redis-server --lazyfree-lazy-user-del yes
    ports:
      - "6379:6379"
  redis-sesamecare-redlock:
    image: redis:8.2.0-alpine
    command: redis-server --lazyfree-lazy-user-del yes
    ports:
      - "6380:6379"
