name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Run docker-compose
        run: docker-compose up -d
      - name: Install npm packages
        run: npm ci
      - name: Test
        run: npm test
