name: Patch Release

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout main
        run: git checkout main
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Publish package
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          npm version patch
          npm publish
          git push origin
